spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
jwt:
  expiration:
    access: 1800000 # 30 * 60 * 1000, 30 minute
    refresh: 259200000 # 3 * 24 * 60 * 60 * 1000, 3 day
  secret: ${JWT_SECRET}
